# Config File for SurgeryWaitTime

default:
  projectName: SurgeryWaitTime

# Config block for synpuf

synpuf:
  databaseName: synpuf110k
  cohortTable: SurgeryWaitTime_synpuf110k
  dbms: !expr keyring::key_get('synpuf_dbms', keyring = 'SurgeryWaitTime')
  user: !expr keyring::key_get('synpuf_user', keyring = 'SurgeryWaitTime')
  password: !expr keyring::key_get('synpuf_password', keyring = 'SurgeryWaitTime')
  connectionString: !expr keyring::key_get('synpuf_connectionString', keyring = 'SurgeryWaitTime')
  cdmDatabaseSchema: !expr keyring::key_get('synpuf_cdmDatabaseSchema', keyring = 'SurgeryWaitTime')
  vocabDatabaseSchema: !expr keyring::key_get('synpuf_vocabDatabaseSchema', keyring = 'SurgeryWaitTime')
  workDatabaseSchema: !expr keyring::key_get('synpuf_workDatabaseSchema', keyring = 'SurgeryWaitTime')
